# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    category.type:
         class: AppBundle\Services\CategoryTypeService
         arguments: ["@doctrine.orm.entity_manager"]
    article.category:
         class: AppBundle\Services\ArticleCategoryService
         arguments: ["@doctrine.orm.entity_manager"]
    annonce:
         class: AppBundle\Services\AnnonceService
         arguments: ["@doctrine.orm.entity_manager"]